<?php 
session_start();
include 'connect.php';

if (!isset($_SESSION["logged_in"]) || $_SESSION['logged_in'] !== true) {
    header("Location: login.php");
    exit;
}

$user_id = $_SESSION['user_id'];
$can_claim = false;
$wait_time = "";

// Check if user can claim daily bonus
$check_sql = "SELECT last_daily_claim FROM users WHERE id = $user_id";
$res = mysqli_query($conn, $check_sql);
$user = mysqli_fetch_assoc($res);

if ($user['last_daily_claim'] === null) {
    $can_claim = true;
} else {
    $last_claim = strtotime($user['last_daily_claim']);
    $now = time();
    $diff = $now - $last_claim;
    if ($diff >= 86400) { // 24 hours
        $can_claim = true;
    } else {
        $remaining = 86400 - $diff;
        $hours = floor($remaining / 3600);
        $minutes = floor(($remaining % 3600) / 60);
        $wait_time = "$hours godz. $minutes min.";
    }
}

include 'header.php';
?>

<div class="container" style="padding: 4rem 0;">
    <h1 style="text-align: center; margin-bottom: 3rem; font-size: 2.5rem; color: var(--gold);">
        Codzienna Skrzynia Bonusowa
    </h1>
    
    <div style="max-width: 800px; margin: 0 auto; background: var(--secondary-dark); border-radius: 20px; padding: 3rem; border: 2px solid var(--gold); box-shadow: 0 0 30px rgba(251, 191, 36, 0.2); text-align: center;">
        <div id="case-container" style="position: relative; width: 100%; height: 250px; overflow: hidden; background: #0a0a0a; border-radius: 12px; margin-bottom: 2rem; border: 1px solid #333; display: flex; align-items: center; justify-content: center;">
            <!-- Indicator line -->
            <div style="position: absolute; top: 0; bottom: 0; left: 50%; width: 4px; background: var(--gold); z-index: 10; box-shadow: 0 0 15px var(--gold);"></div>
            
            <!-- Items track -->
            <div id="case-track" style="display: flex; gap: 10px; position: absolute; left: 0; transition: transform 6s cubic-bezier(0.15, 0, 0.15, 1);">
                <!-- Items will be generated by JS -->
                <div style="min-width: 150px; height: 180px; background: #1a1a1a; border-radius: 8px; display: flex; flex-direction: column; align-items: center; justify-content: center; border: 1px solid #333;">
                    <i class="fas fa-coins" style="font-size: 3rem; color: var(--gold); margin-bottom: 1rem;"></i>
                    <span style="font-weight: bold; font-size: 1.2rem;">? SZC</span>
                </div>
            </div>
        </div>

        <?php if($can_claim): ?>
            <button id="open-case-btn" class="btn btn-gold" style="padding: 1.2rem 3rem; font-size: 1.3rem;">
                <i class="fas fa-box-open"></i> Otwórz Skrzynię Za Darmo!
            </button>
        <?php else: ?>
            <button class="btn btn-secondary" disabled style="padding: 1.2rem 3rem; font-size: 1.3rem;">
                <i class="fas fa-clock"></i> Następna za: <?php echo $wait_time; ?>
            </button>
        <?php endif; ?>
        
        <div id="win-message" style="margin-top: 2rem; font-size: 1.5rem; font-weight: bold; color: var(--success); display: none;">
            Wygrałeś <span id="win-amount">0</span> SZC!
        </div>
    </div>
    
    <div style="margin-top: 4rem; text-align: center;">
        <h3 style="color: var(--text-light); margin-bottom: 1.5rem;">Co możesz wygrać?</h3>
        <div style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap;">
            <div style="padding: 1.5rem; background: var(--secondary-dark); border-radius: 10px; min-width: 120px; border-bottom: 4px solid #94a3b8;">
                <div style="font-size: 1.2rem; font-weight: bold;">50 SZC</div>
                <div style="font-size: 0.8rem; color: var(--text-gray);">Częste</div>
            </div>
            <div style="padding: 1.5rem; background: var(--secondary-dark); border-radius: 10px; min-width: 120px; border-bottom: 4px solid #3b82f6;">
                <div style="font-size: 1.2rem; font-weight: bold;">200 SZC</div>
                <div style="font-size: 0.8rem; color: var(--text-gray);">Rzadkie</div>
            </div>
            <div style="padding: 1.5rem; background: var(--secondary-dark); border-radius: 10px; min-width: 120px; border-bottom: 4px solid #8b5cf6;">
                <div style="font-size: 1.2rem; font-weight: bold;">500 SZC</div>
                <div style="font-size: 0.8rem; color: var(--text-gray);">Epickie</div>
            </div>
            <div style="padding: 1.5rem; background: var(--secondary-dark); border-radius: 10px; min-width: 120px; border-bottom: 4px solid #fbbf24;">
                <div style="font-size: 1.2rem; font-weight: bold;">2500 SZC</div>
                <div style="font-size: 0.8rem; color: var(--text-gray);">Legendarne</div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const track = document.getElementById('case-track');
    const openBtn = document.getElementById('open-case-btn');
    const winMsg = document.getElementById('win-message');
    const winAmt = document.getElementById('win-amount');
    
    if (!openBtn) return;
    
    const possiblePrizes = [
        { val: 50, color: '#94a3b8', weight: 60 },
        { val: 100, color: '#94a3b8', weight: 20 },
        { val: 200, color: '#3b82f6', weight: 10 },
        { val: 500, color: '#8b5cf6', weight: 7 },
        { val: 1000, color: '#8b5cf6', weight: 2 },
        { val: 2500, color: '#fbbf24', weight: 1 }
    ];
    
    // Create items for the track
    let items = [];
    for (let i = 0; i < 50; i++) {
        // Weighted random selection
        let totalWeight = possiblePrizes.reduce((a, b) => a + b.weight, 0);
        let random = Math.random() * totalWeight;
        let selected;
        for (let p of possiblePrizes) {
            if (random < p.weight) {
                selected = p;
                break;
            }
            random -= p.weight;
        }
        items.push(selected);
    }
    
    // Render items
    track.innerHTML = '';
    items.forEach((item, index) => {
        const div = document.createElement('div');
        div.style.minWidth = '150px';
        div.style.height = '180px';
        div.style.background = '#1a1a1a';
        div.style.borderRadius = '8px';
        div.style.display = 'flex';
        div.style.flexDirection = 'column';
        div.style.alignItems = 'center';
        div.style.justifyContent = 'center';
        div.style.border = '1px solid #333';
        div.style.borderBottom = `5px solid ${item.color}`;
        div.innerHTML = `
            <i class="fas fa-coins" style="font-size: 2.5rem; color: var(--gold); margin-bottom: 0.8rem;"></i>
            <span style="font-weight: bold; font-size: 1.1rem;">${item.val} SZC</span>
        `;
        track.appendChild(div);
    });
    
    openBtn.addEventListener('click', function() {
        openBtn.disabled = true;
        
        // Final prize is item at index 45
        const finalPrize = items[45];
        
        // Calculate offset to center index 45 under indicator
        // container width is roughly 800, track items are 150 + 10 gap
        // indicator is at 50% (400px)
        const itemWidth = 160; // 150 + 10
        const offset = (45 * itemWidth) - 400 + 80; // 80 is half item width
        
        track.style.transform = `translateX(-${offset}px)`;
        
        setTimeout(() => {
            // Send result to server
            fetch('claim_daily.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body: `amount=${finalPrize.val}`
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    winAmt.innerText = finalPrize.val;
                    winMsg.style.display = 'block';
                    // Update balance in header
                    const balanceDisplay = document.querySelector('.balance-display');
                    if (balanceDisplay) {
                        balanceDisplay.innerHTML = `<i class="fas fa-coins"></i> ${data.new_balance} SZC`;
                    }
                }
            });
        }, 6500);
    });
});
</script>

<?php include 'footer.php'; ?>
